language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: travis_latest

git:
  depth: 3
  
addons:
  apt:
    packages:
      - imagemagick
      
# Fake X11 server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


install: python -m pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: coveralls
