language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: travis_latest

git:
  depth: 3
  
addons:
  apt:
    packages:
      - imagemagick


install: python -m pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: coveralls
